baseURL      = "https://davideairaghi.netlify.app/"
title        = "Davide Airaghi"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Data Engineer"
  
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My personal website"
  keywords = "homepage, blog"
  images = [""]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorColor    = "#90ee90"

  # Portrait on the home page
    [params.portrait]
      path     = "img/portrait.png"
      alt      = "Portrait"
      maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:airaghi.davide@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/airaghidavide"

  [[params.social]]
    name = "github"
    url  = "https://github.com/airaghidavide"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/airaghi.davide/"

[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "https://davideairaghi.netlify.app/posts/"
  [[menu.main]]
    identifier = "Resume"
    name       = "Resume"
    url        = "Resume/"
